// Writes supabase/migrations/0004_puzzle_data.sql: the solved game table and the puzzle set.
//   npx tsx scripts/gen-puzzles.ts
// The database uses the solver table to check puzzle answers, so it never has to trust the browser.
import { writeFileSync } from 'node:fs';
import { CLASSIC, STREET, type Rules, type State } from '../src/game/rules';
import { evaluate, rankedMoves } from '../src/game/solver';

// Chopsticks is small, so a few rule variants are mixed in to give a bigger puzzle pool.
const MODES: [string, Rules][] = [
  ['classic', CLASSIC],
  ['street', STREET],
  ['rollover', { ...CLASSIC, overflow: 'rollover' }],
  ['selftap', { ...CLASSIC, selfTap: true }],
  ['nosplit', { ...CLASSIC, splits: false, revive: false }],
];

/** Same numbering as the solver and cx_canon in SQL: side to move first, each pair sorted. */
export const canon = (s: State) => {
  const me = s.hands[s.turn], op = s.hands[1 - s.turn];
  return ((Math.min(...me) * 5 + Math.max(...me)) * 5 + Math.min(...op)) * 5 + Math.max(...op);
};

const out: string[] = ['-- Generated by scripts/gen-puzzles.ts. Do not edit by hand.', ''];

for (const [mode, rules] of MODES) {
  // 1. Every canonical position, solved.
  const rows: string[] = [];
  for (let a = 0; a <= 4; a++)
    for (let b = a; b <= 4; b++)
      for (let c = 0; c <= 4; c++)
        for (let d = c; d <= 4; d++) {
          const s: State = { hands: [[a, b], [c, d]], turn: 0 };
          const v = evaluate(rules, s);
          rows.push(`('${mode}', ${canon(s)}, '${v.outcome}', ${v.dtm})`);
        }
  out.push(`insert into public.cx_solver (mode, k, outcome, dtm) values\n  ${rows.join(',\n  ')};`, '');

  // 2. Puzzles: the side to move has a forced win in 2 to 6 moves and only one or two moves keep it fastest.
  const puzzles: string[] = [];
  for (let a = 0; a <= 4; a++)
    for (let b = a; b <= 4; b++)
      for (let c = 0; c <= 4; c++)
        for (let d = c; d <= 4; d++) {
          if (a + b === 0 || c + d === 0) continue;
          const s: State = { hands: [[a, b], [c, d]], turn: 0 };
          const v = evaluate(rules, s);
          if (v.outcome !== 'win' || v.dtm < 3 || v.dtm > 11) continue;
          const ranked = rankedMoves(rules, s);
          const fastest = ranked.filter((r) => r.score === ranked[0].score);
          if (fastest.length > 2 || ranked.length < 3) continue;
          const winning = ranked.filter((r) => r.score > 0).length;
          const myMoves = (v.dtm + 1) / 2;
          const rating =
            400 + Math.min(myMoves, 5) * 220 + // longer lines are harder
            Math.round(250 * (1 - winning / ranked.length)) + // few moves win at all
            (fastest[0].move.kind === 'split' ? 150 : 0) + // splits are easy to overlook
            (fastest.length === 1 ? 50 : 0);
          // Mix up which hand is which so puzzles don't all look sorted.
          const h = (a * 7 + b * 13 + c * 17 + d * 31) % 4;
          const me = h & 1 ? [b, a] : [a, b];
          const op = h & 2 ? [d, c] : [c, d];
          puzzles.push(`('${mode}', '${JSON.stringify(rules)}', '${JSON.stringify([me, op])}', ${myMoves}, ${rating})`);
        }
  out.push(`insert into public.puzzles (mode, rules, hands, moves, rating) values\n  ${puzzles.join(',\n  ')};`, '');
  console.log(`${mode}: ${rows.length} positions, ${puzzles.length} puzzles`);
}

writeFileSync(new URL('../supabase/migrations/0004_puzzle_data.sql', import.meta.url), out.join('\n'));
